//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

pub use super::expenses::Entity as Expenses;
pub use super::expenses_categories::Entity as ExpensesCategories;
pub use super::user::Entity as User;
